spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/websocket
          jwk-set-uri: http://localhost:8080/realms/websocket/protocol/openid-connect/certs